### PR TITLE
changes in responsiveness

### PR DESCRIPTION
**Pull request by Rohanmond**

### CODE REVIEW

**Review by anuj-kumary — APPROVED** [review]
Looks Good!! Ready to merge.

**Review by lomesshh — APPROVED** [review]
heat & clean ! good to go

**Review by ravikumar1002 — CHANGES_REQUESTED** [review]
looks great, 
but I have a one query
that you have to create dev branch and then for every component creates new branch as rohit said  but in your repo I saw that  you created dev and pushed all code in dev branch 
It this ok?  I'm just asking.

**Comment by scjuly19** [comment]
Code looks good, but try to make commit messages more meaningful and try to push less code in a single PR as it would be easy to review.

**Review by scjuly19 — APPROVED** [review]

**Comment by Rohanmond** [comment]
> looks great, but I have a one query that you have to create dev branch and then for every component creates new branch as rohit said but in your repo I saw that you created dev and pushed all code in dev branch It this ok? I'm just asking.

No Actually I forgot to merge landing page in master so I did. Next time I will make branches for components.Thanks

**Pull request merged**
